export const creatorStudioStyles = `
[data-creator-studio],[data-creator-studio] *{box-sizing:border-box}
[data-creator-studio]{min-height:100%;color:var(--dsw-alias-text-primary,#f0f0f4);background:var(--dsw-alias-bg-base,#151517);font:13px/1.45 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
[data-creator-studio] button,[data-creator-studio] input,[data-creator-studio] textarea,[data-creator-studio] select{font:inherit}
[data-creator-studio] button:focus-visible,[data-creator-studio] input:focus-visible,[data-creator-studio] textarea:focus-visible,[data-creator-studio] select:focus-visible{outline:2px solid var(--dsw-alias-border-focus,#79b8ff);outline-offset:2px}
.cs-shell{display:grid;grid-template-rows:auto minmax(0,1fr);min-height:100%}
.cs-header{position:sticky;top:0;z-index:3;display:grid;gap:8px;padding:10px 12px;background:color-mix(in srgb,var(--dsw-alias-bg-layer-1,#1f1f22) 94%,transparent);border-bottom:1px solid var(--dsw-alias-border-l2,rgba(255,255,255,.11));backdrop-filter:blur(14px)}
.cs-heading{display:flex;align-items:center;gap:10px;min-width:0}.cs-heading strong{font-size:14px}.cs-heading span{overflow:hidden;color:var(--dsw-alias-text-tertiary,#96969f);font-size:11px;text-overflow:ellipsis;white-space:nowrap}
.cs-task-nav,.cs-owner-nav,.cs-actions,.cs-badges,.cs-metrics{display:flex;align-items:center;gap:6px;flex-wrap:wrap}
.cs-task-nav button,.cs-owner-nav button,.cs-button{min-height:30px;padding:0 10px;color:var(--dsw-alias-text-secondary,#c2c2c8);background:transparent;border:1px solid var(--dsw-alias-border-l2,rgba(255,255,255,.11));border-radius:8px;cursor:pointer}
.cs-task-nav button:hover,.cs-owner-nav button:hover,.cs-button:hover{color:var(--dsw-alias-text-primary,#fff);background:var(--dsw-alias-fill-hover,rgba(255,255,255,.08))}
.cs-task-nav button[data-active='true'],.cs-owner-nav button[data-active='true'],.cs-button[data-primary='true']{color:#eef7ff;background:color-mix(in srgb,var(--dsw-alias-accent,#548ad8) 28%,transparent);border-color:color-mix(in srgb,var(--dsw-alias-accent,#79b8ff) 62%,transparent)}
.cs-button:disabled,.cs-task-nav button:disabled,.cs-owner-nav button:disabled{opacity:.46;cursor:not-allowed}
.cs-body{display:grid;gap:14px;padding:14px;min-width:0}
.cs-section{display:grid;gap:10px;min-width:0}.cs-section>header{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.cs-section h2,.cs-section h3{margin:0}.cs-section h2{font-size:16px}.cs-section h3{font-size:13px}.cs-muted{margin:0;color:var(--dsw-alias-text-tertiary,#96969f)}
.cs-quick-grid{display:grid;grid-template-columns:repeat(4,minmax(128px,1fr));gap:8px}
.cs-quick-card,.cs-card,.cs-composer,.cs-pulse,.cs-status-panel{display:grid;gap:8px;padding:12px;background:var(--dsw-alias-bg-layer-1,#1e1e21);border:1px solid var(--dsw-alias-border-l2,rgba(255,255,255,.1));border-radius:11px}
.cs-quick-card{min-height:116px;text-align:left;cursor:pointer}.cs-quick-card:hover{background:var(--dsw-alias-bg-elevated,#252529);border-color:color-mix(in srgb,var(--dsw-alias-accent,#79b8ff) 45%,transparent)}.cs-quick-card strong{font-size:14px}.cs-quick-card span{color:var(--dsw-alias-text-tertiary,#96969f);font-size:11px}.cs-quick-card b{display:grid;place-items:center;width:28px;height:28px;border-radius:8px;background:color-mix(in srgb,var(--cs-accent,#79b8ff) 20%,transparent);color:var(--cs-accent,#9bcbff)}
.cs-owner-grid{display:grid;grid-template-columns:repeat(3,minmax(150px,1fr));gap:8px}.cs-owner-row{display:grid;grid-template-columns:auto minmax(0,1fr);gap:8px;align-items:center;padding:9px 10px;border-radius:9px;background:var(--dsw-alias-bg-layer-1,#1e1e21);border:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.07))}.cs-owner-row strong{font-size:12px}.cs-owner-row small{display:block;overflow:hidden;color:var(--dsw-alias-text-tertiary,#96969f);text-overflow:ellipsis;white-space:nowrap}
.cs-status-dot{width:9px;height:9px;border-radius:50%;background:#777}.cs-status-dot[data-status='ready'],.cs-status-dot[data-status='completed']{background:#51c58b}.cs-status-dot[data-status='running']{background:#6aa8ff}.cs-status-dot[data-status='partial'],.cs-status-dot[data-status='stale'],.cs-status-dot[data-status='approval_required']{background:#f0b45a}.cs-status-dot[data-status='offline'],.cs-status-dot[data-status='failed'],.cs-status-dot[data-status='contract_mismatch'],.cs-status-dot[data-status='reconcile_required'],.cs-status-dot[data-status='unknown']{background:#ee6b72}
.cs-stage-track{display:grid;grid-template-columns:repeat(6,minmax(88px,1fr));gap:6px}.cs-stage{position:relative;display:grid;gap:5px;padding:9px;border-radius:9px;background:var(--dsw-alias-bg-layer-2,#27272b);border:1px solid transparent}.cs-stage[data-current='true']{border-color:var(--dsw-alias-accent,#79b8ff)}.cs-stage small{color:var(--dsw-alias-text-tertiary,#96969f)}
.cs-progress{height:4px;overflow:hidden;border-radius:999px;background:rgba(255,255,255,.08)}.cs-progress>i{display:block;height:100%;background:var(--dsw-alias-accent,#79b8ff);border-radius:inherit}
.cs-resource-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:8px}.cs-card{align-content:start;min-height:128px}.cs-card[data-kind='image'],.cs-card[data-kind='video'],.cs-card[data-kind='shot']{min-height:164px}.cs-card-preview{display:grid;place-items:center;min-height:70px;border-radius:8px;background:linear-gradient(135deg,rgba(93,135,193,.18),rgba(192,105,170,.12));color:var(--dsw-alias-text-tertiary,#a0a0aa);font-size:22px}.cs-card h3{font-size:13px}.cs-card p{margin:0;color:var(--dsw-alias-text-secondary,#bdbdc5);font-size:11px}.cs-badge,.cs-metric{display:inline-flex;align-items:center;min-height:20px;padding:0 7px;border-radius:999px;background:rgba(255,255,255,.07);color:var(--dsw-alias-text-secondary,#c6c6cc);font-size:10px}.cs-metric[data-tone='positive']{color:#75d8a5}.cs-metric[data-tone='warning']{color:#f3c16c}.cs-metric[data-tone='critical']{color:#ff858b}
.cs-waveform{height:52px;display:flex;align-items:center;gap:2px;padding:6px;border-radius:8px;background:rgba(0,0,0,.16)}.cs-waveform i{flex:1;min-width:2px;background:linear-gradient(#7fb9ff,#b18cff);border-radius:2px}
.cs-diff{display:grid;grid-template-columns:1fr 1fr;gap:6px}.cs-diff pre{min-height:70px;margin:0;padding:8px;overflow:auto;white-space:pre-wrap;border-radius:7px;background:rgba(0,0,0,.16);color:var(--dsw-alias-text-secondary,#c6c6cc);font:11px/1.45 ui-monospace,SFMono-Regular,Consolas,monospace}.cs-diff pre[data-side='after']{background:rgba(64,139,92,.12)}
.cs-workspace-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(260px,.36fr);gap:12px;align-items:start}.cs-composer{position:sticky;top:112px}.cs-field{display:grid;gap:5px}.cs-field>span{font-size:11px;font-weight:650}.cs-field input,.cs-field textarea,.cs-field select{width:100%;min-height:34px;padding:7px 9px;color:inherit;background:var(--dsw-alias-bg-layer-2,#29292d);border:1px solid var(--dsw-alias-border-l2,rgba(255,255,255,.12));border-radius:8px}.cs-field textarea{min-height:84px;resize:vertical}.cs-confirm{display:flex;gap:8px;align-items:flex-start;color:var(--dsw-alias-text-secondary,#c6c6cc);font-size:11px}.cs-receipt{padding:9px;border-radius:8px;background:rgba(96,143,207,.11);border:1px solid rgba(111,169,245,.2)}.cs-receipt[data-status='unknown'],.cs-receipt[data-status='reconcile_required'],.cs-receipt[data-status='failed']{background:rgba(197,70,77,.1);border-color:rgba(238,107,114,.28)}
.cs-list{display:grid;gap:6px;margin:0;padding:0;list-style:none}.cs-list li{display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:9px;align-items:center;padding:9px 10px;border-radius:8px;background:var(--dsw-alias-bg-layer-1,#1e1e21);border:1px solid var(--dsw-alias-border-l1,rgba(255,255,255,.07))}.cs-list strong{font-size:12px}.cs-list small{display:block;color:var(--dsw-alias-text-tertiary,#96969f)}
.cs-empty{display:grid;place-items:center;gap:8px;min-height:150px;padding:24px;text-align:center;color:var(--dsw-alias-text-tertiary,#96969f)}
.cs-alert{padding:10px;border-radius:8px;color:#ffd4d6;background:rgba(198,69,77,.12);border:1px solid rgba(238,107,114,.25)}
@media(max-width:1050px){.cs-quick-grid{grid-template-columns:repeat(2,minmax(140px,1fr))}.cs-owner-grid{grid-template-columns:repeat(2,minmax(140px,1fr))}.cs-stage-track{grid-template-columns:repeat(3,minmax(96px,1fr))}.cs-workspace-grid{grid-template-columns:1fr}.cs-composer{position:static}}
@media(max-width:600px){.cs-body{padding:10px}.cs-quick-grid,.cs-owner-grid,.cs-stage-track{grid-template-columns:1fr}.cs-owner-nav{display:none}.cs-resource-grid{grid-template-columns:1fr}.cs-diff{grid-template-columns:1fr}.cs-composer [data-risk='medium'],.cs-composer [data-risk='high']{opacity:.55}}
@media(prefers-reduced-motion:reduce){[data-creator-studio] *{scroll-behavior:auto!important;transition:none!important}}
`
