// @vitest-environment jsdom
import { afterEach, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { EikonaPreparationForm } from '../src/eikona-preparation-form.tsx'
import { defaultCreatorStudioTranslator as t } from '../src/locales.ts'
afterEach(cleanup)
it.each([
  ['permission_denied', '当前身份无权访问'], ['invalid_input', '准备输入无效'], ['needs_contract', '准备服务合同尚未匹配'],
] as const)('explains %s without discarding the input', async (status, message) => {
  const prepare = vi.fn(async () => ({ status }))
  render(<EikonaPreparationForm prepare={prepare} available t={t} />)
  fireEvent.change(screen.getByLabelText('提示词 ID'), { target: { value: 'prompt' } })
  fireEvent.click(screen.getByRole('button', { name: '创建准备' }))
  await screen.findByText(text => text.startsWith(message))
  expect((screen.getByLabelText('提示词 ID') as HTMLInputElement).value).toBe('prompt')
  expect(prepare).toHaveBeenCalledOnce()
})
it('submits optional size and seed as controls and rejects fractional seeds', async () => {
  const prepare = vi.fn(async () => ({ status: 'unavailable' as const }))
  render(<EikonaPreparationForm prepare={prepare} available t={t} />)
  fireEvent.change(screen.getByLabelText('提示词 ID'), { target: { value: 'prompt' } })
  fireEvent.change(screen.getByLabelText('尺寸（可选）'), { target: { value: ' 1024x1024 ' } })
  fireEvent.change(screen.getByLabelText('随机种子（可选整数）'), { target: { value: '1.5' } })
  expect((screen.getByRole('button', { name: '创建准备' }) as HTMLButtonElement).disabled).toBe(true)
  fireEvent.change(screen.getByLabelText('随机种子（可选整数）'), { target: { value: '42' } })
  fireEvent.click(screen.getByRole('button', { name: '创建准备' }))
  expect(prepare).toHaveBeenCalledWith(expect.objectContaining({ controls: { model_ref: 'openai/gpt-5.4-image-2', candidate_count: 1, size: '1024x1024', seed: 42 } }))
  await screen.findByText(/未能创建准备/u)
})
it('preserves multiline variable content and rejects duplicate names', async () => {
  const prepare = vi.fn(async () => ({ status: 'unavailable' as const }))
  render(<EikonaPreparationForm prepare={prepare} available t={t} />)
  fireEvent.change(screen.getByLabelText('提示词 ID'), { target: { value: 'prompt-one' } })
  fireEvent.click(screen.getByRole('button', { name: '添加变量' }))
  fireEvent.change(screen.getByLabelText('变量名 1'), { target: { value: ' subject ' } })
  fireEvent.change(screen.getByLabelText('变量内容 1'), { target: { value: '第一行\n第二行=保留' } })
  fireEvent.click(screen.getByRole('button', { name: '添加变量' }))
  fireEvent.change(screen.getByLabelText('变量名 2'), { target: { value: 'subject' } })
  expect((screen.getByRole('button', { name: '创建准备' }) as HTMLButtonElement).disabled).toBe(true)
  fireEvent.click(screen.getByRole('button', { name: '移除变量 2' }))
  fireEvent.click(screen.getByRole('button', { name: '创建准备' }))
  expect(prepare).toHaveBeenCalledWith(expect.objectContaining({ values: { subject: '第一行\n第二行=保留' } }))
  await screen.findByText(/未能创建准备/u)
})
it('associates input constraints with invalid fields and rejects invalid versions', () => {
  const prepare = vi.fn()
  render(<EikonaPreparationForm prepare={prepare} available t={t} />)
  const prompt = screen.getByLabelText('提示词 ID'), version = screen.getByLabelText('固定版本')
  fireEvent.change(prompt, { target: { value: 'bad/prompt' } })
  fireEvent.change(version, { target: { value: '0' } })
  expect(prompt.getAttribute('aria-invalid')).toBe('true')
  expect(version.getAttribute('aria-invalid')).toBe('true')
  expect(document.getElementById(version.getAttribute('aria-describedby')!)?.textContent).toContain('整数')
  fireEvent.submit(prompt.closest('form')!)
  expect(prepare).not.toHaveBeenCalled()
})
it('reports edited drafts to the existing leave guard even after preparation succeeds', async () => {
  const dirty = vi.fn()
  const prepare = vi.fn(async () => ({ status: 'ready' as const, preparationRef: `egp_${'a'.repeat(64)}`, projectId: 'project', promptRef: 'eikona://prompts/prompt-one/versions/1', promptDigest: 'b'.repeat(64), digest: 'c'.repeat(64), summaryDigest: 'd'.repeat(64), modelRef: 'openai/gpt-5.4-image-2', candidateCount: 1 as const, costState: 'unknown' as const, executionAuthorized: false as const, createdAt: '2026-09-09T00:00:00Z', controls: { model_ref: 'openai/gpt-5.4-image-2', candidate_count: 1 as const } }))
  render(<EikonaPreparationForm prepare={prepare} available t={t} onDirty={dirty} />)
  expect(dirty).toHaveBeenLastCalledWith(false)
  fireEvent.change(screen.getByLabelText('提示词 ID'), { target: { value: 'prompt-one' } })
  expect(dirty).toHaveBeenLastCalledWith(true)
  fireEvent.click(screen.getByRole('button', { name: '创建准备' }))
  await screen.findByText(/准备已创建/u)
  expect(dirty).toHaveBeenLastCalledWith(true)
  fireEvent.change(screen.getByLabelText('提示词 ID'), { target: { value: '' } })
  expect(dirty).toHaveBeenLastCalledWith(false)
})
it('does not submit during composition and permits an explicit submit afterward', async () => {
  const prepare = vi.fn(async () => ({ status: 'unavailable' as const }))
  render(<EikonaPreparationForm prepare={prepare} available t={t} />)
  const input = screen.getByLabelText('提示词 ID')
  fireEvent.change(input, { target: { value: 'prompt-one' } })
  fireEvent.compositionStart(input)
  fireEvent.submit(input.closest('form')!)
  expect(prepare).not.toHaveBeenCalled()
  fireEvent.compositionEnd(input)
  fireEvent.click(screen.getByRole('button', { name: '创建准备' }))
  expect(prepare).toHaveBeenCalledOnce()
  await screen.findByText(/未能创建准备/u)
})
it('submits a fixed version once and retains the draft after an unknown result', async () => {
  let finish!: (value: { status: 'unconfirmed' }) => void
  const prepare = vi.fn(() => new Promise<{ status: 'unconfirmed' }>(resolve => { finish = resolve }))
  render(<EikonaPreparationForm prepare={prepare} available t={t} />)
  fireEvent.change(screen.getByLabelText('提示词 ID'), { target: { value: 'prompt-one' } })
  fireEvent.change(screen.getByLabelText('固定版本'), { target: { value: '3' } })
  fireEvent.click(screen.getByRole('button', { name: '创建准备' }))
  fireEvent.click(screen.getByRole('button', { name: '正在创建准备…' }))
  expect(prepare).toHaveBeenCalledOnce()
  expect(prepare).toHaveBeenCalledWith({ prompt_id: 'prompt-one', prompt_version: 3, controls: { model_ref: 'openai/gpt-5.4-image-2', candidate_count: 1 } })
  finish({ status: 'unconfirmed' })
  await screen.findByText(/准备结果未确认/u)
  expect((screen.getByLabelText('提示词 ID') as HTMLInputElement).value).toBe('prompt-one')
  expect((screen.getByRole('button', { name: '创建准备' }) as HTMLButtonElement).disabled).toBe(true)
})
it('explains unavailable preparation and never submits', () => {
  const prepare = vi.fn()
  render(<EikonaPreparationForm prepare={prepare} available={false} t={t} />)
  expect(screen.getByRole('status').textContent).toContain('未开放')
  expect(prepare).not.toHaveBeenCalled()
})
