// @vitest-environment jsdom
import { afterEach, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { EikonaRunCandidates } from '../src/eikona-run-candidates.tsx'
import { defaultCreatorStudioTranslator as t } from '../src/locales.ts'
afterEach(cleanup)
const runId = `run_owner_${'a'.repeat(32)}`
const result = { status: 'ready' as const, runId, projectId: 'one', observedAt: '2026-09-09T00:00:00Z', ownerDecision: 'pending' as const, admissionState: 'unknown' as const, canDecide: false, canSupersede: false, candidates: [{ candidateId: 'one', label: 'Candidate one', artifactRef: `eikona://artifacts/${runId}/one`, contentDigest: 'b'.repeat(64) }] }
it('loads only the explicit run on user request and preserves a fixed asset reference', async () => {
  const read = vi.fn(async () => result)
  render(<EikonaRunCandidates runId={runId} read={read} t={t} />)
  expect(read).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: '读取本次生成候选' }))
  await screen.findByText('Candidate one')
  expect(screen.getByText(result.candidates[0]!.artifactRef)).toBeTruthy()
  expect(read).toHaveBeenCalledExactlyOnceWith({ runId })
})
it('rejects another run rather than replacing the requested candidates', async () => {
  render(<EikonaRunCandidates runId={runId} read={async () => ({ ...result, runId: 'other', candidates: [] })} t={t} />)
  fireEvent.click(screen.getByRole('button', { name: '读取本次生成候选' }))
  await screen.findByText(/无法读取本次候选/u)
  expect(screen.queryByText('Candidate one')).toBeNull()
})
it('selects a fixed candidate only on click and rejects a substituted selection', async () => {
  const select = vi.fn(async () => ({ status: 'selected' as const, selection: { artifactRef: result.candidates[0]!.artifactRef, contentDigest: 'c'.repeat(64) } }))
  render(<EikonaRunCandidates runId={runId} read={async () => result} select={select} t={t} />)
  fireEvent.click(screen.getByRole('button', { name: '读取本次生成候选' }))
  await screen.findByText('Candidate one')
  expect(select).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: '选择此候选' }))
  await screen.findByText(/未能确认选择/u)
  expect(select).toHaveBeenCalledExactlyOnceWith({ selection: { artifactRef: result.candidates[0]!.artifactRef, contentDigest: result.candidates[0]!.contentDigest } })
})
it('shows the selected fixed digest and clears local selection feedback on reload', async () => {
  const select = vi.fn(async () => ({ status: 'selected' as const, selection: { artifactRef: result.candidates[0]!.artifactRef, contentDigest: result.candidates[0]!.contentDigest } }))
  render(<EikonaRunCandidates runId={runId} read={async () => result} select={select} t={t} />)
  fireEvent.click(screen.getByRole('button', { name: '读取本次生成候选' }))
  await screen.findByText(result.candidates[0]!.contentDigest)
  fireEvent.click(screen.getByRole('button', { name: '选择此候选' }))
  await screen.findByText('候选选择已核验；采用需要单独确认。')
  expect(screen.getByRole('button', { name: '选择此候选' }).getAttribute('aria-pressed')).toBe('true')
  fireEvent.click(screen.getByRole('button', { name: '读取本次生成候选' }))
  expect(screen.getByRole('button', { name: '选择此候选' }).getAttribute('aria-pressed')).toBe('false')
})
it('requires separate media confirmation and preserves the exact candidate version on denied access', async () => {
  const readImage = vi.fn(async () => ({ status: 'unavailable' as const }))
  render(<EikonaRunCandidates runId={runId} read={async () => result} readImage={readImage} t={t} />)
  fireEvent.click(screen.getByRole('button', { name: '读取本次生成候选' }))
  await screen.findByText('Candidate one')
  expect(readImage).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: '预览图片' }))
  expect(readImage).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: '确认读取图片' }))
  await screen.findByText('图片读取失败，当前成果未被修改。')
  expect(readImage).toHaveBeenCalledExactlyOnceWith({ artifactRef: result.candidates[0]!.artifactRef, contentDigest: result.candidates[0]!.contentDigest, confirmed: true, idempotencyKey: expect.any(String) })
  expect(screen.getByText(result.candidates[0]!.contentDigest)).toBeTruthy()
})
it('compares two fixed candidates only after confirmation and clears comparison on reload', async () => {
  const candidates = [0, 1, 2].map(index => ({ candidateId: `item-${index}`, label: `Image ${index}`, artifactRef: `eikona://artifacts/${runId}/item-${index}`, contentDigest: String(index + 1).repeat(64) }))
  const readImage = vi.fn(async () => ({ status: 'unavailable' as const }))
  render(<EikonaRunCandidates runId={runId} read={async () => ({ ...result, candidates })} readImage={readImage} t={t} />)
  fireEvent.click(screen.getByRole('button', { name: '读取本次生成候选' }))
  await screen.findByText('Image 0')
  const choices = screen.getAllByRole('button', { name: '选入比较' })
  fireEvent.click(choices[0]!)
  fireEvent.click(choices[1]!)
  expect((choices[2] as HTMLButtonElement).disabled).toBe(true)
  expect(readImage).not.toHaveBeenCalled()
  fireEvent.click(screen.getByRole('button', { name: '确认读取并比较' }))
  await screen.findByText('图片读取失败，当前成果未被修改。')
  expect(readImage).toHaveBeenCalledTimes(2)
  for (let index = 0; index < 2; index++) expect(readImage).toHaveBeenNthCalledWith(index + 1, expect.objectContaining({ artifactRef: candidates[index]!.artifactRef, contentDigest: candidates[index]!.contentDigest, confirmed: true }))
  fireEvent.click(screen.getByRole('button', { name: '读取本次生成候选' }))
  expect(screen.queryByRole('button', { name: '确认读取并比较' })).toBeNull()
  expect(readImage).toHaveBeenCalledTimes(2)
})
