/**
 * First-party bearer-token authentication for the DSH web transport.
 *
 * This is a local transport-admission layer: it verifies an opaque token the
 * deployment operator created, grants remote clients access to the /api bridge
 * and its two WebSocket downlinks, and lets an authenticated admin reach the
 * methods that remain loopback-only without authentication.
 */

import { createHash, randomBytes, timingSafeEqual } from 'node:crypto'
import { readFile } from 'node:fs/promises'
import type { IncomingHttpHeaders } from 'node:http'

/** Scopes a DSH access token can carry. */
export type DshTokenScope = 'web' | 'tui' | 'admin'

/** One accepted opaque token and the scopes it grants. */
export interface DshTokenAuthToken {
  /** Opaque token value; DSH never logs or persists the plaintext. */
  readonly token: string
  /** Scopes granted by this token. Defaults to `['admin']`. */
  readonly scopes?: readonly DshTokenScope[]
}

/** Explicit configuration for the built-in token gate. */
export type DshTokenAuthConfig = {
  /** Legacy compatibility ingress; production should use storePath. */
  readonly tokens: readonly DshTokenAuthToken[]
  readonly storePath?: never
  readonly sessionTtlMs?: number
} | {
  /** Digest-only token store generated by `dsh auth token`. */
  readonly storePath: string
  readonly tokens?: never
  readonly sessionTtlMs?: number
}

/** The transport facts the gate reads from either HTTP representation. */
export interface DshTokenAuthRequest {
  readonly headers: IncomingHttpHeaders | Headers
}

/** Successful authentication result. */
export interface DshTokenAuthResult {
  /** Scopes granted by the matched token. */
  readonly scopes: ReadonlySet<DshTokenScope>
  /** Stable token metadata id; never the secret. */
  readonly tokenId: string
}

/** HTTPS cookie carrying an opaque browser session, never the access token. */
export const DSH_SESSION_COOKIE = '__Host-dsh-session'

/** Local HTTP fallback cookie for direct single-user DSH. */
export const DSH_SESSION_COOKIE_FALLBACK = 'dsh-session'

/** Default header carrying the token for non-browser clients. */
export const DSH_ACCESS_TOKEN_HEADER = 'x-dsh-access-token'

function header(headers: IncomingHttpHeaders | Headers, name: string): string | undefined {
  if (headers instanceof Headers) return headers.get(name) ?? undefined
  const value = headers[name.toLowerCase()]
  return typeof value === 'string' ? value : undefined
}

function readCookie(headers: IncomingHttpHeaders | Headers, name: string): string | undefined {
  const cookie = header(headers, 'cookie')
  if (cookie === undefined) return undefined
  for (const part of cookie.split(';')) {
    const index = part.indexOf('=')
    if (index === -1) continue
    if (part.slice(0, index).trim() === name) return part.slice(index + 1).trim()
  }
  return undefined
}

function readBearerToken(headers: IncomingHttpHeaders | Headers): string | undefined {
  const authorization = header(headers, 'authorization')
  if (authorization !== undefined) {
    const match = /^Bearer\s+(.+)$/i.exec(authorization.trim())
    if (match !== null) return match[1]?.trim()
  }
  return header(headers, DSH_ACCESS_TOKEN_HEADER)
}

function readSession(headers: IncomingHttpHeaders | Headers): string | undefined {
  return readCookie(headers, DSH_SESSION_COOKIE)
    ?? readCookie(headers, DSH_SESSION_COOKIE_FALLBACK)
}

function safeEqual(a: string, b: string): boolean {
  const left = Buffer.from(a)
  const right = Buffer.from(b)
  return left.length === right.length && timingSafeEqual(left, right)
}

function normalizeScopes(scopes: readonly DshTokenScope[] | undefined): ReadonlySet<DshTokenScope> {
  const values: readonly DshTokenScope[] = scopes === undefined || scopes.length === 0 ? ['admin'] : scopes
  const result = new Set<DshTokenScope>(values)
  if (result.size === 0) result.add('admin')
  return result
}

function digest(value: string): string {
  return createHash('sha256').update(value).digest('hex')
}

interface StoredToken {
  readonly id: string
  readonly tokenHash: string
  readonly scopes: readonly DshTokenScope[]
  readonly expiresAt?: string
  readonly revokedAt?: string
}

interface StoredTokenFile {
  readonly version: 1
  readonly tokens: readonly StoredToken[]
}

interface BrowserSession {
  readonly tokenId: string
  readonly scopes: ReadonlySet<DshTokenScope>
  readonly expiresAt: number
}

const DEFAULT_SESSION_TTL_MS = 12 * 60 * 60 * 1000

/**
 * Verifies opaque bearer tokens for HTTP and WebSocket admission.
 *
 * The gate is deliberately stateless: token revocation and expiry are handled
 * by the token store/operator before a token is placed in configuration, or by
 * a future persistent store. It never writes token values to logs.
 */
export class DshTokenGate {
  private readonly entries: { readonly id: string; readonly token: string; readonly scopes: ReadonlySet<DshTokenScope> }[]
  private readonly storePath: string | undefined
  private readonly sessionTtlMs: number
  private readonly sessions = new Map<string, BrowserSession>()

  /** @param config - accepted tokens and their scopes. */
  constructor(config: DshTokenAuthConfig) {
    if ('storePath' in config) {
      if (typeof config.storePath !== 'string' || config.storePath.length === 0) {
        throw new Error('client-connection: tokenAuth.storePath must be a non-empty path')
      }
      this.storePath = config.storePath
      this.entries = []
    } else {
      if (!Array.isArray(config.tokens) || config.tokens.length === 0) {
        throw new Error('client-connection: tokenAuth.tokens must contain at least one token')
      }
      this.entries = config.tokens.map((entry, index) => {
        if (typeof entry.token !== 'string' || entry.token.length === 0) {
          throw new Error('client-connection: tokenAuth token must be a non-empty opaque value')
        }
        return { id: `legacy-${String(index)}`, token: entry.token, scopes: normalizeScopes(entry.scopes) }
      })
    }
    this.sessionTtlMs = config.sessionTtlMs ?? DEFAULT_SESSION_TTL_MS
    if (!Number.isSafeInteger(this.sessionTtlMs) || this.sessionTtlMs <= 0) {
      throw new Error('client-connection: tokenAuth.sessionTtlMs must be a positive integer')
    }
  }

  /**
   * Authenticate one request and return its granted scopes.
   * @param request - request headers.
   * @returns matched scopes, or undefined when no token is valid.
   */
  async authenticate(request: DshTokenAuthRequest): Promise<DshTokenAuthResult | undefined> {
    const bearer = readBearerToken(request.headers)
    if (bearer !== undefined) return this.authenticateToken(bearer)
    const session = readSession(request.headers)
    if (session === undefined) return undefined
    const key = digest(session)
    const found = this.sessions.get(key)
    if (found === undefined || found.expiresAt <= Date.now()) {
      this.sessions.delete(key)
      return undefined
    }
    if (this.storePath !== undefined && await this.storedToken(found.tokenId) === undefined) {
      this.sessions.delete(key)
      return undefined
    }
    return { tokenId: found.tokenId, scopes: found.scopes }
  }

  /**
   * Authenticate one raw token value.
   * @param token - presented opaque token.
   * @returns matched scopes, or undefined when the token is invalid.
   */
  async authenticateToken(token: string): Promise<DshTokenAuthResult | undefined> {
    if (token === '') return undefined
    for (const entry of this.entries) {
      if (safeEqual(entry.token, token)) return { tokenId: entry.id, scopes: entry.scopes }
    }
    if (this.storePath === undefined) return undefined
    const separator = token.indexOf('_', 'dshw_'.length)
    if (!token.startsWith('dshw_') || separator === -1) return undefined
    const tokenId = token.slice('dshw_'.length, separator)
    const stored = await this.storedToken(tokenId)
    if (stored === undefined || !safeEqual(stored.tokenHash, digest(token))) return undefined
    return { tokenId: stored.id, scopes: normalizeScopes(stored.scopes) }
  }

  /** Exchange a long-lived token for an opaque in-memory browser session. */
  async exchangeToken(token: string): Promise<{ session: string; expiresAt: number } | undefined> {
    const auth = await this.authenticateToken(token)
    if (auth === undefined) return undefined
    const session = randomBytes(32).toString('base64url')
    const expiresAt = Date.now() + this.sessionTtlMs
    this.sessions.set(digest(session), { tokenId: auth.tokenId, scopes: auth.scopes, expiresAt })
    return { session, expiresAt }
  }

  /** Delete the presented browser session, if any. */
  logout(request: DshTokenAuthRequest): void {
    const session = readSession(request.headers)
    if (session !== undefined) this.sessions.delete(digest(session))
  }

  /**
   * Whether an HTTP request may enter the authenticated API bridge.
   * @param request - request headers.
   * @returns true for any valid token.
   */
  async authorizeHttp(request: DshTokenAuthRequest): Promise<boolean> {
    return await this.authenticate(request) !== undefined
  }

  /**
   * Whether a WebSocket upgrade may open an event downlink.
   * @param request - upgrade request headers.
   * @returns true for any valid token.
   */
  async authorizeWebSocket(request: DshTokenAuthRequest): Promise<boolean> {
    return await this.authenticate(request) !== undefined
  }

  /**
   * Whether the request carries a token with the `admin` scope.
   * @param request - request headers.
   * @returns true when an admin-scoped token is present.
   */
  async authorizeAdmin(request: DshTokenAuthRequest): Promise<boolean> {
    return (await this.authenticate(request))?.scopes.has('admin') ?? false
  }

  private async storedToken(tokenId: string): Promise<StoredToken | undefined> {
    if (this.storePath === undefined) return undefined
    let content: string
    try {
      content = await readFile(this.storePath, 'utf8')
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined
      throw error
    }
    const parsed = JSON.parse(content) as Partial<StoredTokenFile>
    if (parsed.version !== 1 || !Array.isArray(parsed.tokens)) {
      throw new Error('client-connection: unsupported token store')
    }
    const now = Date.now()
    return parsed.tokens.find(candidate => candidate.id === tokenId
      && candidate.revokedAt === undefined
      && (candidate.expiresAt === undefined || Date.parse(candidate.expiresAt) > now))
  }
}
