import { useMemo, useState } from 'react'
import type { Template } from '@yeisme/dsh-template-registry'
export interface TemplateStudioProps { templates: Template[]; connected?: boolean; onUse?: (template: Template) => void; onExport?: (template: Template) => void }
export function TemplateStudio({ templates, connected = true, onUse, onExport }: TemplateStudioProps) {
  const [query, setQuery] = useState(''); const [selected, setSelected] = useState<Template | undefined>(templates[0])
  const filtered = useMemo(() => templates.filter(t => `${t.title} ${t.summary} ${t.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [templates, query])
  return <div data-template-studio className="template-studio">
    <style>{`[data-template-studio]{font:13px system-ui;color:var(--vk-text-primary,#ececf1);background:var(--vk-bg-base,#171719);height:100%;display:flex;flex-direction:column}[data-template-studio] *{box-sizing:border-box}.ts-bar{padding:12px 14px;border-bottom:1px solid var(--vk-border-l1,rgba(255,255,255,.06));display:flex;justify-content:space-between;gap:12px}.ts-body{display:grid;grid-template-columns:180px minmax(220px,1fr) minmax(240px,1fr);min-height:0;flex:1}.ts-nav,.ts-list,.ts-detail{padding:12px;overflow:auto}.ts-nav{border-right:1px solid var(--vk-border-l1,rgba(255,255,255,.06))}.ts-detail{border-left:1px solid var(--vk-border-l1,rgba(255,255,255,.06))}.ts-search{width:100%;height:34px;background:#242429;color:inherit;border:1px solid #45454d;border-radius:6px;padding:0 8px;margin-bottom:10px}.ts-row{display:block;width:100%;text-align:left;background:transparent;color:inherit;border:0;border-bottom:1px solid rgba(255,255,255,.06);padding:10px 8px;cursor:pointer}.ts-row[data-selected=true]{background:rgba(101,166,255,.18)}.ts-muted{color:var(--vk-text-tertiary,#92929b)}.ts-actions{display:flex;gap:8px;margin-top:16px}.ts-button{height:30px;border:1px solid #555;color:inherit;background:#343438;border-radius:6px;padding:0 10px;cursor:pointer}.ts-button:disabled{opacity:.5;cursor:not-allowed}@media(max-width:720px){.ts-body{grid-template-columns:1fr}.ts-nav,.ts-detail{border:0}.ts-detail{border-top:1px solid rgba(255,255,255,.06)}}`}</style>
    <header className="ts-bar"><strong>Template Studio</strong><span className="ts-muted">{connected ? 'Registry connected' : 'Registry unavailable · using last safe catalog'}</span></header>
    <div className="ts-body"><nav className="ts-nav"><div className="ts-muted">Library</div><div>All templates</div><div className="ts-muted" style={{marginTop:12}}>Recent</div></nav><main className="ts-list"><input aria-label="Search templates" className="ts-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Search templates" />{filtered.length===0 ? <div className="ts-muted">No matching templates</div> : filtered.map(t => <button className="ts-row" data-selected={selected?.ref===t.ref} key={t.ref} onClick={() => setSelected(t)}><strong>{t.title}</strong><div className="ts-muted">{t.summary}</div><small>{t.maturity} · {t.tags.join(' · ')}</small></button>)}</main><aside className="ts-detail">{selected ? <><h2>{selected.title}</h2><p className="ts-muted">{selected.summary}</p><p>Ref: <code>{selected.ref}</code></p><p>Digest: <code>{selected.digest}</code></p><p>Rights: preview {selected.rights.preview?'allowed':'restricted'} · export {selected.rights.export?'allowed':'restricted'}</p><div className="ts-actions"><button className="ts-button" onClick={() => onUse?.(selected)}>Use template</button><button className="ts-button" disabled={!selected.rights.export} title={!selected.rights.export?'Export is not permitted':''} onClick={() => onExport?.(selected)}>Export package</button></div></> : <div className="ts-muted">Select a template</div>}</aside></div>
  </div>
}
