export type { ProjectionFreshness, SafeProjectionMeta, BoundedSummary } from './projection.js'
export type { PreferenceStorage } from './browser.js'
export { browserPreferenceStorage } from './browser.js'
export { probeCapability } from './probe.js'
export type { ProbeDegradation, ProbeResult } from './probe.js'
export { composeDisposers, subscriptionHandle } from './dispose.js'
export type { Disposable, Disposer, SubscribeFace, SubscriptionHandle } from './dispose.js'
