import { expect, test } from '@playwright/test'

for (const width of [360, 560, 960]) for (const lang of ['zh', 'en']) for (const theme of ['light', 'dark']) {
  test(`search discovery ${width}px ${lang} ${theme}`, async ({ page }, info) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.setViewportSize({ width, height: 850 })
    await page.goto(`/search-center?width=${width}&lang=${lang}&theme=${theme}`)
    const input = page.getByRole('combobox', { name: /Search sessions|搜索会话/ })
    await expect(input).toBeVisible()
    const discovery = page.getByRole('region', { name: lang === 'en' ? 'Explore by category' : '按分类探索' })
    await expect(discovery.getByRole('button')).toHaveCount(8)
    const sidebar = page.locator('.pwr-search-sidebar')
    if (width > 720) {
      await expect(sidebar).toBeVisible()
      const unselected = sidebar.getByRole('button', { name: lang === 'en' ? 'Recent resources' : '最近访问', exact: true })
      expect(await unselected.evaluate(element => getComputedStyle(element).backgroundColor.replace(/\s/g, ''))).toBe('rgba(0,0,0,0)')
      expect(await unselected.evaluate(element => getComputedStyle(element).color)).toBe(await page.locator('.pwr-search-surface').evaluate(element => getComputedStyle(element).color))
    }
    else await expect(sidebar).toBeHidden()
    const bounds = await input.boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(width)
    await page.screenshot({ path: info.outputPath('discovery.png'), fullPage: true })
    expect(await page.locator('.pwr-search-category-grid').evaluate(element => getComputedStyle(element).gridTemplateColumns.split(' ').length)).toBeLessThanOrEqual(3)
    await input.fill('Document')
    const results = page.getByRole('listbox', { name: lang === 'en' ? 'Search results' : '搜索结果' })
    await expect(results.getByRole('option')).toHaveCount(5)
    await page.getByRole('button', { name: lang === 'en' ? 'View all' : '查看全部', exact: true }).click()
    await expect(results.getByRole('option')).toHaveCount(9)
    await page.screenshot({ path: info.outputPath('results.png'), fullPage: true })
    if (width > 720) {
      await sidebar.getByRole('button', { name: lang === 'en' ? 'Tools and capabilities' : '工具与能力', exact: true }).click()
      await sidebar.getByRole('button', { name: /Skills/ }).click()
    } else if (width > 420) {
      await page.getByRole('combobox', { name: lang === 'en' ? 'Resource category' : '资源分类' }).selectOption('skill')
    } else {
      await page.getByRole('button', { name: lang === 'en' ? 'Browse categories' : '浏览分类', exact: true }).click()
      const panel = page.getByRole('dialog', { name: lang === 'en' ? 'Browse categories' : '浏览分类' })
      await panel.getByRole('button', { name: lang === 'en' ? 'Tools and capabilities' : '工具与能力', exact: true }).click()
      await panel.getByRole('button', { name: /Skills/ }).click()
      await expect(panel).toHaveCount(0)
    }
    await expect(input).toHaveValue('Document')
    await expect(results.getByRole('option')).toHaveCount(0)
    await expect(page.getByText(lang === 'en'
      ? 'This category is not connected to search yet. Your query is kept; choose another category to continue.'
      : '此分类尚未接入搜索。已保留查询，可选择其他分类继续。')).toBeVisible()
    expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
    expect(errors).toEqual([])
  })
}

test('search dialog keeps editing keys and does not execute during selection', async ({ page }, info) => {
  await page.goto('/search-center?width=560&lang=en&mode=dialog')
  const dialog = page.getByRole('dialog', { name: 'Search and open' })
  const input = dialog.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Inspect')
  await input.press('End')
  await input.press('ArrowLeft')
  expect(await input.evaluate(element => (element as HTMLInputElement).selectionStart)).toBe(6)
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
  await page.screenshot({ path: info.outputPath('dialog.png'), fullPage: true })
})

test('metadata conditions search beyond the first page and preserve query scope', async ({ page }, info) => {
  await page.goto('/search-center?width=960&lang=en&case=metadata')
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Planning')
  await page.getByLabel('Updated since (UTC)').fill('2026-01-01')
  await page.getByRole('combobox', { name: 'Resource status' }).selectOption('running')
  await page.getByRole('combobox', { name: 'Sort within each group' }).selectOption('updated')
  const results = page.getByRole('listbox', { name: 'Search results' })
  await expect(results.getByRole('option')).toHaveCount(1)
  await expect(results.getByRole('option', { name: 'Planning newest' })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Search scope' })).toHaveValue('all')
  await expect(page.getByText('Pane and command catalogs do not provide update times; they are excluded by this time condition.')).toBeVisible()
  await page.screenshot({ path: info.outputPath('metadata-filter.png'), fullPage: true })
})

test('workspace scope survives clearing conditions and loses results on revocation', async ({ page }, info) => {
  await page.goto('/search-center?width=560&lang=en&case=scope')
  const scope = page.getByRole('combobox', { name: 'Search scope' })
  await expect(scope).toHaveValue('workspace:w1')
  await page.getByRole('combobox', { name: /Search sessions/ }).fill('Planning')
  await scope.selectOption('workspace:w2')
  const hit = page.getByRole('listbox', { name: 'Search results' }).getByRole('option', { name: 'Planning w2' })
  await expect(hit).toBeVisible()
  await hit.click()
  await expect.poll(() => page.evaluate(() => (window as any).fixtureOpenedWorkspace)).toBe('w2')
  await page.getByRole('combobox', { name: 'Sort within each group' }).selectOption('name')
  await expect(page.getByText('This source does not support the selected filters or sorting. Its unfiltered results are not shown.')).toBeVisible()
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await expect(scope).toHaveValue('workspace:w2')
  await page.evaluate(() => (window as any).revokeSearchScope())
  await expect(scope).toHaveValue('workspace:w2')
  await expect(hit).toHaveCount(0)
  await expect(page.locator('.pwr-search-state')).toContainText('Selected project is unavailable')
  await page.screenshot({ path: info.outputPath('scope-revoked.png'), fullPage: true })
})

for (const width of [360, 1200]) test(`read-only preview layout ${width}px`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 850 })
  await page.goto(`/search-center?width=${width}&lang=en`)
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Document')
  await expect(page.getByRole('option', { name: 'Document 0' })).toBeVisible()
  await page.getByRole('button', { name: 'Preview selected result' }).click()
  const preview = page.getByRole('complementary', { name: 'Read-only preview' })
  await expect(preview).toBeVisible()
  await expect(preview.getByRole('heading', { name: 'Document 0' })).toBeFocused()
  const main = page.locator('.pwr-search-main')
  if (width === 360) await expect(main).toBeHidden()
  else {
    await expect(main).toBeVisible()
    expect((await preview.boundingBox())!.width).toBe(320)
    expect((await main.boundingBox())!.width).toBeGreaterThanOrEqual(480)
  }
  expect(await page.evaluate(() => window.document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  await page.screenshot({ path: info.outputPath('preview.png'), fullPage: true })
  await preview.getByRole('button', { name: 'Back to results' }).click()
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('Document')
  await expect(main).toBeVisible()
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
})

test('dialog continues into a newly mounted search pane without losing selection or restoring old focus', async ({ page }) => {
  await page.goto('/search-center?width=960&lang=en&case=handoff')
  const dialog = page.getByRole('dialog')
  const input = dialog.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Document')
  await expect(dialog.getByRole('option', { name: 'Document 0' })).toBeVisible()
  await input.press('ArrowDown')
  await expect(dialog.getByRole('option', { name: 'Document 1' })).toHaveAttribute('aria-selected', 'true')
  await dialog.getByRole('button', { name: 'Pin search as a pane' }).click()
  await expect(dialog).toHaveCount(0)
  const destination = page.getByRole('combobox', { name: /Search sessions/ })
  await expect(destination).toHaveValue('Document')
  await expect(destination).toBeFocused()
  await expect(page.getByRole('option', { name: 'Document 1' })).toHaveAttribute('aria-selected', 'true')
  expect(await page.evaluate(() => (window as any).fixtureRestoredFocus)).toBeUndefined()
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
})

test('an unmounted handoff destination times out without closing or clearing the dialog', async ({ page }) => {
  await page.goto('/search-center?width=960&lang=en&case=handoff-missing')
  const dialog = page.getByRole('dialog')
  const input = dialog.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Document')
  await dialog.getByRole('button', { name: 'Pin search as a pane' }).click()
  await expect(dialog).toBeVisible()
  await expect(dialog.getByText('The search pane could not be opened. Your query and filters are kept here.')).toBeVisible()
  await expect(input).toHaveValue('Document')
  await expect(dialog.getByRole('button', { name: 'Pin search as a pane' })).toBeEnabled()
  expect(await page.evaluate(() => (window as any).fixtureRestoredFocus)).toBeUndefined()
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
})

test('owner metadata removal clears an open preview and re-queries without changing the query', async ({ page }) => {
  await page.goto('/search-center?width=560&lang=en&case=metadata')
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Planning newest')
  await expect(page.getByRole('listbox').getByRole('option', { name: 'Planning newest' })).toBeVisible()
  await page.getByRole('button', { name: 'Preview selected result' }).click()
  const preview = page.getByRole('complementary', { name: 'Read-only preview' })
  await expect(preview.getByRole('heading', { name: 'Planning newest' })).toBeVisible()
  await page.evaluate(() => (window as any).removeSearchMetadata())
  await expect(preview.getByRole('heading', { name: 'Planning newest' })).toHaveCount(0)
  await expect(preview.getByRole('status')).toContainText('no longer')
  await expect(preview.getByRole('button', { name: 'Open with source owner' })).toHaveCount(0)
  await preview.getByRole('button', { name: 'Back to results' }).click()
  await expect(input).toHaveValue('Planning newest')
  await expect(page.getByRole('listbox').getByRole('option')).toHaveCount(0)
})

test('result actions disable unsupported floating and confirm a split next to the existing anchor', async ({ page }) => {
  await page.goto('/search-center?width=960&lang=en&case=layout')
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Document 0')
  const result = page.getByRole('option', { name: 'Document 0' })
  await expect(result).toBeVisible()
  await expect(result.getByRole('button')).toHaveCount(0)
  await page.getByRole('button', { name: 'Open actions for Document 0', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: 'Open floating' })).toBeDisabled()
  await page.getByRole('menuitem', { name: 'Open to the right' }).click()
  const state = await page.evaluate(() => (window as any).searchLayoutSnapshot())
  const views = Object.values(state.views) as any[]
  expect(views.find(view => view.kind === 'fixture.docs.0').groupId).not.toBe(views.find(view => view.kind === 'fixture.docs.8').groupId)
  expect(state.maximizedGroupId).toBeUndefined()
  await expect(input).toHaveValue('Document 0')
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
})

for (const mode of ['pane', 'dialog']) test(`result menu keyboard navigation and focus return in ${mode}`, async ({ page }) => {
  await page.goto(`/search-center?width=560&lang=en&mode=${mode}`)
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Document 0')
  await expect(page.getByRole('option', { name: 'Document 0' })).toBeVisible()
  await input.press('Shift+F10')
  const first = page.getByRole('menuitem', { name: 'Open to the right' })
  await expect(first).toBeFocused()
  await first.press('End')
  const last = page.getByRole('menuitem', { name: 'Open below' })
  await expect(last).toBeFocused()
  await last.press('ArrowDown')
  await expect(first).toBeFocused()
  await first.press('Escape')
  await expect(page.getByRole('menu')).toHaveCount(0)
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('Document 0')
  if (mode === 'dialog') await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
})

test('dialog cycles Tab boundaries, skips hidden results in preview and admits its own portal menu', async ({ page }) => {
  await page.goto('/search-center?width=560&lang=en&mode=dialog')
  await page.evaluate(() => { const button = document.createElement('button'); button.textContent = 'Neighbour pane'; document.body.append(button) })
  const dialog = page.getByRole('dialog')
  const input = dialog.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Document 0')
  await expect(dialog.getByRole('option', { name: 'Document 0' })).toBeVisible()
  const first = dialog.getByRole('button', { name: 'Pin search as a pane' })
  const last = dialog.locator('button:visible:not(:disabled):not([tabindex="-1"])').last()
  await last.focus()
  await last.press('Tab')
  await expect(first).toBeFocused()
  await first.press('Shift+Tab')
  await expect(last).toBeFocused()
  await dialog.getByRole('button', { name: 'Actions for selected result' }).click()
  const menuFirst = page.getByRole('menuitem', { name: 'Open to the right' })
  await expect(menuFirst).toBeFocused()
  await menuFirst.press('Tab')
  await expect(page.getByRole('menu')).toHaveCount(0)
  expect(await dialog.evaluate(element => element.contains(document.activeElement))).toBe(true)
  await dialog.getByRole('button', { name: 'Preview selected result' }).click()
  const heading = dialog.getByRole('heading', { name: 'Document 0' })
  await expect(heading).toBeFocused()
  await heading.press('Tab')
  const ownerOpen = dialog.getByRole('button', { name: 'Open with source owner' })
  await expect(ownerOpen).toBeFocused()
  await ownerOpen.press('Tab')
  await expect(first).toBeFocused()
  await first.press('Shift+Tab')
  await expect(ownerOpen).toBeFocused()
  await dialog.getByRole('button', { name: 'Back to results' }).click()
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('Document 0')
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
})

test('search pane does not trap Tab before an adjacent pane control', async ({ page }) => {
  await page.goto('/search-center?width=560&lang=en&mode=pane')
  await page.evaluate(() => { const button = document.createElement('button'); button.textContent = 'Neighbour pane'; document.body.append(button) })
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Document 0')
  await expect(page.getByRole('option', { name: 'Document 0' })).toBeVisible()
  const last = page.locator('[data-workspace-search="pane"] button:visible:not(:disabled):not([tabindex="-1"])').last()
  await last.focus()
  await last.press('Tab')
  await expect(page.getByRole('button', { name: 'Neighbour pane' })).toBeFocused()
})

test('coarse pointer controls and official menu items meet 44px touch targets', async ({ browser }) => {
  const context = await browser.newContext({ viewport: { width: 360, height: 850 }, hasTouch: true, reducedMotion: 'reduce' })
  try {
    const page = await context.newPage()
    await page.goto('http://127.0.0.1:4178/search-center?width=360&lang=en&mode=pane')
    expect(await page.evaluate(() => matchMedia('(pointer:coarse)').matches)).toBe(true)
    const input = page.getByRole('combobox', { name: /Search sessions/ })
    await input.fill('Document 0')
    await expect(page.getByRole('option', { name: 'Document 0' })).toBeVisible()
    const undersized = await page.locator('[data-workspace-search="pane"]').evaluate(root =>
      [...root.querySelectorAll<HTMLElement>('button,input,select')].filter(element => element.getClientRects().length > 0)
        .filter(element => { const rect = element.getBoundingClientRect(); return rect.width < 44 || rect.height < 44 })
        .map(element => element.getAttribute('aria-label') ?? element.textContent))
    expect(undersized).toEqual([])
    await page.getByRole('button', { name: 'Actions for selected result' }).tap()
    const first = page.getByRole('menuitem', { name: 'Open to the right' })
    await expect(first).toBeVisible()
    for (const item of await page.getByRole('menuitem').all()) {
      const rect = await item.boundingBox()
      expect(rect!.height).toBeGreaterThanOrEqual(44)
      expect(rect!.width).toBeGreaterThanOrEqual(44)
    }
    expect(await page.locator('[data-workspace-search="pane"]').evaluate(element => getComputedStyle(element).transitionDuration)).toBe('0s')
    expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
  } finally { await context.close() }
})

test('narrow pane uses filter panels inside a wide viewport and restores state after container resize', async ({ page }) => {
  await page.setViewportSize({ width: 1200, height: 850 })
  await page.goto('/search-center?width=360&lang=en')
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Document')
  await expect(page.getByRole('combobox', { name: 'Search scope' })).toBeVisible()
  await expect(page.getByRole('combobox', { name: 'Sort within each group' })).toHaveCount(0)
  const trigger = page.getByRole('button', { name: 'Search filters', exact: true })
  await trigger.click()
  const panel = page.getByRole('dialog', { name: 'Search filters' })
  await expect(panel.getByRole('heading', { name: 'Search filters' })).toBeFocused()
  await panel.getByRole('combobox', { name: 'Sort within each group' }).selectOption('name')
  await panel.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(panel).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await expect(input).toHaveValue('Document')
  await trigger.click()
  await expect(panel.getByRole('combobox', { name: 'Sort within each group' })).toHaveValue('name')
  await page.locator('#fixture').evaluate(element => { (element as HTMLElement).style.width = '960px' })
  await expect(panel).toHaveCount(0)
  await expect(input).toBeFocused()
  await expect(page.getByRole('combobox', { name: 'Sort within each group' })).toHaveValue('name')
  await expect(page.locator('.pwr-search-sidebar')).toBeVisible()
  await expect(trigger).toHaveCount(0)
})

test('nested compact panel Escape returns to the search dialog without closing it', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 850 })
  await page.goto('/search-center?width=360&lang=en&mode=dialog')
  const search = page.getByRole('dialog', { name: 'Search and open', exact: true })
  const trigger = search.getByRole('button', { name: 'Browse categories', exact: true })
  await trigger.click()
  const categories = page.getByRole('dialog', { name: 'Browse categories', exact: true })
  await categories.getByRole('heading', { name: 'Browse categories' }).press('Escape')
  await expect(categories).toHaveCount(0)
  await expect(search).toBeVisible()
  await expect(trigger).toBeFocused()
})

test('registered resources honor scope, expand a category and preview without execution', async ({ page }) => {
  await page.goto('/search-center?width=960&lang=en&case=providers')
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Review skill')
  await expect(page.getByText('The source does not support the current scope or conditions', { exact: true })).toBeVisible()
  const results = page.getByRole('listbox')
  await expect(results.getByRole('option')).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Search scope' }).selectOption('all')
  await expect(results.getByRole('option')).toHaveCount(5)
  await results.getByRole('button', { name: 'View all', exact: true }).click()
  await expect(results.getByRole('option')).toHaveCount(7)
  await page.getByRole('button', { name: 'Preview selected result' }).click()
  const preview = page.getByRole('complementary', { name: 'Read-only preview' })
  await expect(preview.getByRole('heading', { name: 'Review skill 0' })).toBeVisible()
  await expect(preview.getByText('v1', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => (window as any).fixtureResourceOpened)).toBeUndefined()
  await preview.getByRole('button', { name: 'Open with source owner' }).click()
  expect(await page.evaluate(() => (window as any).fixtureResourceOpened)).toEqual({ ref: 'skill:0', revision: 'v1', scope: { kind: 'profile' } })
  await page.evaluate(() => (window as any).removeResourceSource())
  await expect(preview.getByRole('heading', { name: 'Review skill 0' })).toHaveCount(0)
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
})

test('installed directory uses the Tools owner and opens disabled Skill details without a write', async ({ page }) => {
  await page.setViewportSize({ width: 1100, height: 900 })
  await page.goto('/search-center?width=960&lang=en&case=tools-owner')
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('skill:review')
  const result = page.getByRole('option', { name: 'review', exact: true })
  await expect(result).toBeVisible()
  await expect(result).toContainText('disabled')
  await result.click()
  const owner = page.locator('[data-mcp-inspector][data-active-section="details"]')
  await expect(owner).toBeVisible()
  await expect(owner.locator('.tools-detail-title strong')).toHaveText('review')
  await expect(owner.locator('.tools-details-pane')).toContainText('fixture-provider')
  await expect(owner.locator('.tools-details-pane')).toContainText('Disabled')
  await owner.getByRole('button', { name: 'Read document' }).click()
  await expect(owner.getByText('This host has no file-document reader contract for this Skill.')).toBeVisible()
  expect(await page.evaluate(() => (window as any).fixtureEnableCalls)).toBe(0)
  expect(await page.evaluate(() => (window as any).fixtureOwnerWrites)).toBe(0)
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
})

test('explicit Skill reading pages source text and clears it on denied continuation without execution', async ({ page }) => {
  let externalRequests = 0
  page.on('request', request => { if (request.url().includes('example.invalid')) externalRequests += 1 })
  await page.setViewportSize({ width: 1100, height: 900 })
  await page.goto('/search-center?width=960&lang=en&case=tools-reader')
  await page.getByRole('combobox', { name: /Search sessions/ }).fill('skill:review')
  await page.getByRole('option', { name: 'review', exact: true }).click()
  const owner = page.locator('[data-mcp-inspector][data-active-section="details"]')
  expect(await page.evaluate(() => (window as any).fixtureDocumentReads)).toBe(0)
  await owner.getByRole('button', { name: 'Read document' }).click()
  const source = owner.getByLabel('Skill document source')
  await expect(source).toContainText('# Review guide')
  await expect(source).toContainText('<em>plain markup</em>')
  await expect(source.locator('a,img,em,script')).toHaveCount(0)
  await owner.getByRole('button', { name: 'Read next section' }).click()
  await expect(source).toHaveText('Second section')
  await owner.getByRole('button', { name: 'Previous section' }).click()
  await expect(source).toContainText('# Review guide')
  await page.evaluate(() => { (window as any).fixtureDocumentDenied = true })
  await owner.getByRole('button', { name: 'Read next section' }).click()
  await expect(source).toHaveCount(0)
  await expect(owner.getByText('This document is not accessible. Read content has been cleared.')).toBeVisible()
  expect(externalRequests).toBe(0)
  expect(await page.evaluate(() => (window as any).fixtureEnableCalls)).toBe(0)
  expect(await page.evaluate(() => (window as any).fixtureOwnerWrites)).toBe(0)
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
})

test('restoring a delayed selection never opens an available substitute on Enter', async ({ page }) => {
  await page.goto('/search-center?width=960&lang=en&case=restore-selection')
  await page.evaluate(() => {
    const fixture = document.getElementById('fixture')!
    const form = document.createElement('form')
    fixture.replaceWith(form); form.appendChild(fixture)
    ;(window as any).fixtureSubmits = 0
    form.addEventListener('submit', event => { event.preventDefault(); (window as any).fixtureSubmits++ })
  })
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await expect(input).toHaveValue('Document')
  await expect(page.getByText('The previous selection is not available yet. Wait for its source or choose another result.')).toBeVisible()
  await input.press('Enter')
  expect(await page.evaluate(() => Object.values((window as any).searchLayoutSnapshot().views).length)).toBe(0)
  expect(await page.evaluate(() => (window as any).fixtureExpectedOpened)).toBeUndefined()
  expect(await page.evaluate(() => (window as any).fixtureSubmits)).toBe(0)
  await expect.poll(() => page.evaluate(() => typeof (window as any).releaseHandoffResult)).toBe('function')
  await page.evaluate(() => (window as any).releaseHandoffResult())
  await expect(page.getByRole('option', { name: 'Document skill' })).toHaveAttribute('aria-selected', 'true')
  await input.press('Enter')
  await expect.poll(() => page.evaluate(() => (window as any).fixtureExpectedOpened)).toBe(true)
  expect(await page.evaluate(() => Object.values((window as any).searchLayoutSnapshot().views).length)).toBe(0)
})


test('session scope filters original metadata and remains selected after clear and owner removal', async ({ page }, info) => {
  await page.goto('/search-center?case=metadata&mode=pane&width=960&lang=en')
  const scope = page.getByRole('combobox', { name: 'Search scope' })
  await scope.selectOption('session:newest')
  await expect(scope).toHaveValue('session:newest')
  await page.getByRole('combobox', { name: /Search sessions/ }).fill('Planning')
  const results = page.getByRole('listbox', { name: 'Search results' })
  await expect(results.getByRole('option', { name: 'Planning newest' })).toBeVisible()
  await expect(results.getByRole('option')).toHaveCount(1)
  await page.getByRole('button', { name: 'Clear filters', exact: true }).click()
  await expect(scope).toHaveValue('session:newest')
  await page.evaluate(() => (window as any).removeSearchMetadata())
  await expect(scope).toHaveValue('session:newest')
  await expect(results.getByRole('option')).toHaveCount(0)
  await expect(page.locator('.pwr-search-state')).toContainText('Selected session is unavailable')
  await page.screenshot({ path: info.outputPath('session-scope-revoked.png'), fullPage: true })
})


for (const mode of ['pane', 'dialog']) test(`search ${mode} follows a controlled keyboard visual viewport without resizing its host`, async ({ page }, info) => {
  await page.setViewportSize({ width: 360, height: 850 })
  await page.addInitScript(() => {
    const viewport = Object.assign(new EventTarget(), { width: 360, height: 850, offsetTop: 0, offsetLeft: 0 })
    Object.defineProperty(window, 'visualViewport', { configurable: true, value: viewport })
    ;(window as any).setSearchViewport = (height: number, offsetTop: number) => {
      Object.assign(viewport, { height, offsetTop }); viewport.dispatchEvent(new Event('resize'))
    }
  })
  await page.goto(`/search-center?width=360&lang=en&mode=${mode}`)
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Document')
  const root = page.locator('[data-workspace-search]')
  await page.evaluate(() => (window as any).setSearchViewport(340, 50))
  const bounded = mode === 'pane' ? root : page.locator('.pwr-search-modal')
  await expect(bounded).toHaveAttribute('data-search-visual-viewport', mode)
  const bounds = await root.boundingBox()
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(390)
  expect(await page.evaluate(() => window.innerHeight)).toBe(850)
  await input.scrollIntoViewIfNeeded()
  expect((await input.boundingBox())!.y).toBeGreaterThanOrEqual(50)
  await expect(input).toHaveValue('Document')
  const footer = page.locator('.pwr-search-footer')
  await footer.scrollIntoViewIfNeeded()
  const footerBounds = await footer.boundingBox()
  expect(footerBounds!.y + footerBounds!.height).toBeLessThanOrEqual(390)
  await page.screenshot({ path: info.outputPath('keyboard-viewport.png'), fullPage: true })
  await page.evaluate(() => (window as any).setSearchViewport(850, 0))
  await expect(bounded).not.toHaveAttribute('data-search-visual-viewport')
  expect(await root.evaluate(element => element.scrollTop)).toBe(0)
  await expect(input).toBeVisible()
  await expect(input).toHaveValue('Document')
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
})

for (const mode of ['pane', 'dialog']) test(`search ${mode} reflows at the CSS viewport equivalent of 200 percent desktop zoom`, async ({ browser }, info) => {
  // 960x850 physical pixels at scale 2: 480x425 CSS pixels. This validates
  // browser reflow geometry, not a browser-toolbar zoom command or screen reader.
  const context = await browser.newContext({ viewport: { width: 480, height: 425 }, deviceScaleFactor: 2 })
  try {
    const page = await context.newPage()
    await page.goto(`/search-center?width=560&lang=en&mode=${mode}`)
    await page.locator('#fixture').evaluate(element => { element.style.width = '100%'; element.style.height = '100vh' })
    const input = page.getByRole('combobox', { name: /Search sessions/ })
    await input.fill('Document 0')
    const result = page.getByRole('listbox').getByRole('option', { name: 'Document 0' })
    await expect(result).toBeVisible()
    await page.getByRole('button', { name: 'Preview selected result' }).click()
    const back = page.getByRole('button', { name: 'Back to results' })
    await back.scrollIntoViewIfNeeded()
    const bounds = await back.boundingBox()
    expect(bounds!.x).toBeGreaterThanOrEqual(0)
    expect(bounds!.y).toBeGreaterThanOrEqual(0)
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(480)
    expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(425)
    await back.click()
    await expect(input).toHaveValue('Document 0')
    if (mode === 'dialog') {
      const close = page.getByRole('button', { name: 'Close view selector' })
      await close.scrollIntoViewIfNeeded()
      await expect(close).toBeVisible()
    }
    await page.screenshot({ path: info.outputPath('zoom-200-equivalent.png'), fullPage: true })
    expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
  } finally { await context.close() }
})

for (const theme of ['light', 'dark']) test(`search text and keyboard focus contrast in ${theme}`, async ({ page }) => {
  await page.goto(`/search-center?width=960&lang=en&theme=${theme}`)
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.focus()
  const contrast = await input.evaluate(element => {
    const field = element.closest('.pwr-search-input')!
    const background = getComputedStyle(field).backgroundColor
    const style = getComputedStyle(element)
    const canvas = document.createElement('canvas'); canvas.width = 1; canvas.height = 1
    const ctx = canvas.getContext('2d')!
    const luminance = (color: string) => {
      ctx.clearRect(0, 0, 1, 1); ctx.fillStyle = background; ctx.fillRect(0, 0, 1, 1)
      ctx.fillStyle = color; ctx.fillRect(0, 0, 1, 1)
      const values = [...ctx.getImageData(0, 0, 1, 1).data].slice(0, 3).map(value => {
        const channel = value / 255; return channel <= 0.04045 ? channel / 12.92 : ((channel + 0.055) / 1.055) ** 2.4
      })
      return values[0]! * 0.2126 + values[1]! * 0.7152 + values[2]! * 0.0722
    }
    const base = luminance(background)
    const ratio = (color: string) => { const foreground = luminance(color); return (Math.max(base, foreground) + 0.05) / (Math.min(base, foreground) + 0.05) }
    return { text: ratio(style.color), focus: ratio(style.outlineColor), outline: style.outlineStyle }
  })
  expect(contrast.text).toBeGreaterThanOrEqual(4.5)
  expect(contrast.outline).not.toBe('none')
  expect(contrast.focus).toBeGreaterThanOrEqual(3)
})

test('search announces visible results and owner removal politely, suppresses IME, and retains one clear action', async ({ page }, info) => {
  await page.goto('/search-center?width=560&lang=en&case=metadata')
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  const live = page.locator('.pwr-search-announcement')
  await expect(live).toHaveAttribute('aria-live', 'polite')
  await expect(live).toHaveAttribute('aria-atomic', 'true')
  await input.dispatchEvent('compositionstart')
  await input.fill('Planning newest')
  await expect(live).toHaveText('')
  await input.dispatchEvent('compositionend', { data: 'Planning newest' })
  await expect(live).toContainText('1 result currently shown')
  await expect(live).not.toContainText('Planning')
  await expect(page.getByRole('button', { name: 'Clear search', exact: true })).toHaveCount(1)
  await page.screenshot({ path: info.outputPath('single-clear-action.png'), fullPage: true })
  await page.evaluate(() => (window as any).removeSearchMetadata())
  await expect(live).toContainText('previously selected result is no longer shown')
  await expect(live).toContainText('0 results currently shown')
  await page.getByRole('button', { name: 'Clear search', exact: true }).click()
  await expect(input).toHaveValue('')
  await expect(input).toBeFocused()
  await expect(live).toHaveText('')
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
})

test('directory search opens the original Explorer only after its receiver selects the owner target', async ({ page }, info) => {
  await page.goto('/search-center?width=560&lang=en&case=files')
  await page.getByRole('combobox', { name: /Search sessions/ }).fill('Reports')
  await page.getByRole('listbox').getByRole('option', { name: 'Reports' }).click()
  await expect(page.getByRole('dialog', { name: 'Search and open' })).toHaveCount(0)
  const selected = page.locator('[data-explorer-ref="dir:reports"]')
  await expect(selected).toBeVisible()
  await expect(selected).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('tree', { name: 'Explorer' })).toBeFocused()
  expect(await page.evaluate(() => (window as any).fixtureFolderBodyReads)).toBe(0)
  await page.screenshot({ path: info.outputPath('located-directory.png'), fullPage: true })
  await page.getByRole('button', { name: 'Back to previous Explorer view' }).click()
  await expect(page.getByText('original.txt', { exact: true })).toBeVisible()
  await expect(selected).toHaveCount(0)
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
})

test('editing a query cancels a pending Explorer location and ignores its late owner response', async ({ page }) => {
  await page.goto('/search-center?width=560&lang=en&case=files')
  await page.evaluate(() => { (window as any).fixtureFolderRevealPaused = true })
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Reports')
  await page.getByRole('listbox').getByRole('option', { name: 'Reports' }).click()
  await expect.poll(() => page.evaluate(() => typeof (window as any).releaseFolderReveal)).toBe('function')
  await input.fill('Changed')
  await expect.poll(() => page.evaluate(() => (window as any).folderRevealActive())).toBe(false)
  await page.evaluate(() => (window as any).releaseFolderReveal())
  await expect.poll(() => page.evaluate(() => (window as any).fixtureFolderRevealSettled)).toBe(true)
  await expect(page.getByRole('dialog', { name: 'Search and open' })).toBeVisible()
  await expect(input).toHaveValue('Changed')
  await expect(input).toBeFocused()
  await expect(page.locator('[data-explorer-ref="dir:reports"]')).toHaveCount(0)
  expect(await page.evaluate(() => (window as any).fixtureFolderBodyReads)).toBe(0)
  expect(await page.evaluate(() => (window as any).fixtureExecutions)).toBe(0)
})

test('project canvas owner searches nodes and opens the original canvas Pane', async ({ page }, info) => {
  await page.goto('/search-center?width=960&lang=en&case=canvas')
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Launch')
  const result = page.getByRole('listbox').getByRole('option', { name: 'Launch brief' })
  await expect(result).toBeVisible()
  await result.click()
  await expect.poll(() => page.evaluate(() => (window as any).canvasOpened)).toBeTruthy()
  expect(await page.evaluate(() => (window as any).canvasOpened?.kind)).toBe('creator.canvas')
  await page.screenshot({ path: info.outputPath('canvas-open.png'), fullPage: true })
})

test('canvas owner scope changes invalidate old results without widening to another project', async ({ page }) => {
  await page.goto('/search-center?width=960&lang=en&case=canvas')
  const input = page.getByRole('combobox', { name: /Search sessions/ })
  await input.fill('Launch')
  await expect(page.getByRole('listbox').getByRole('option', { name: 'Launch brief' })).toBeVisible()
  await page.evaluate(() => (window as any).canvasProjectChanged())
  await input.fill('Launch')
  await expect(page.getByRole('listbox').getByRole('option', { name: 'Launch brief' })).toHaveCount(0)
  await expect(page.locator('.pwr-search-state')).toContainText(/unavailable|no matching|not connected/i)
})
