import { expect, test } from '@playwright/test'

for (const width of [360, 560, 960]) {
  test(`Session subagents ${width}: compact tree, details and binding`, async ({ page }, info) => {
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
    await page.goto(`/agent-surfaces?width=${width}`)
    const writer = page.getByRole('button', { name: /^Implementation.*可继续/ })
    await expect(writer).toBeVisible()
    await writer.focus(); await page.keyboard.press('ArrowRight')
    await expect(page.getByRole('button', { name: /^Checks.*单次/ })).toBeVisible()
    await page.keyboard.press('Enter')
    const detail = page.locator('[data-pane-subagent-detail]')
    await expect(detail).toBeVisible()
    await expect(detail.getByRole('heading')).toBeFocused()
    expect((await detail.boundingBox())!.y).toBeLessThan(200)
    const row = page.locator('[data-pane-subagent-node="writer"]')
    if (width > 720) expect(Math.abs((await row.boundingBox())!.y - (await detail.boundingBox())!.y)).toBeLessThan(100)
    expect(await page.locator('[data-pane-subagent-monitor]').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
    await page.screenshot({ path: info.outputPath(`subagents-${width}.png`), fullPage: true })
    await page.evaluate(() => (window as any).agentFixture.switchSession())
    await expect(page.getByText('OTHER SESSION')).toHaveCount(0)
    await page.getByRole('button', { name: '返回列表' }).click()
    await expect(writer).toBeFocused()
    await page.getByLabel('搜索子 Agent').fill('Checks')
    await expect(page.getByRole('button', { name: /^Checks.*单次/ })).toBeVisible()
    expect(await page.evaluate(() => (window as any).agentFixture.calls)).toEqual([])
    expect(errors).toEqual([])
  })
  test(`Agent Team ${width}: user projects and Ordo navigation`, async ({ page }, info) => {
    const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
    await page.goto(`/agent-surfaces?mode=team&width=${width}`)
    await expect(page.getByText('用户工作区 · Ordo')).toBeVisible()
    await page.screenshot({ path: info.outputPath(`teams-home-${width}.png`), fullPage: true })
    await page.getByRole('button', { name: /Ordo · 工程交付/ }).click()
    await expect(page.getByRole('button', { name: /实现会话作用域/ })).toBeVisible()
    await page.getByRole('tab', { name: 'Agent', exact: true }).click()
    await page.getByRole('button', { name: /Implementer/ }).click()
    await expect(page.getByRole('heading', { name: 'Implementer' })).toBeVisible()
    await page.screenshot({ path: info.outputPath(`team-roster-${width}.png`), fullPage: true })
    await page.evaluate(() => (window as any).agentFixture.switchSession())
    await expect(page.getByLabel('项目', { exact: true })).toHaveValue('project.a')
    expect(await page.locator('[data-ordo-project]').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
    await page.getByLabel('项目', { exact: true }).selectOption('project.b')
    await expect(page.getByRole('button', { name: /整理引用/ })).toBeVisible()
    expect(errors).toEqual([])
  })
}
test('English subagent labels and 200% rendered scale retain controls', async ({ page }) => {
  await page.goto('/agent-surfaces?width=560&lang=en')
  await page.getByLabel('Search subagents').fill('Implementation')
  await page.getByRole('button', { name: /^Implementation.*Continuable/ }).click()
  // Rendered scaling is a layout stress check, not an OS/browser zoom claim.
  await page.locator('#fixture').evaluate(el => { (el as HTMLElement).style.zoom = '2' })
  await expect(page.getByRole('button', { name: 'Back to list' })).toBeVisible()
  await page.getByRole('button', { name: 'Back to list' }).click()
  await expect(page.getByLabel('Search subagents')).toBeVisible()
})

test('Single inactive subagent stays at the top with a long label', async ({ page }, info) => {
  await page.goto('/agent-surfaces?width=960')
  await expect(page.getByRole('button', { name: /^Implementation.*可继续/ })).toBeVisible()
  await page.evaluate(() => (window as any).agentFixture.single())
  await page.getByRole('button', { name: /^Inactive researcher.*可继续/ }).click()
  const detail = page.locator('[data-pane-subagent-detail]')
  expect((await detail.boundingBox())!.y).toBeLessThan(200)
  await expect(page.getByRole('button', { name: '停止', exact: true })).toBeDisabled()
  expect(await detail.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: info.outputPath('subagents-single-long.png'), fullPage: true })
})
