import { test, expect } from '@playwright/test'

for (const width of [360, 560, 960]) for (const lang of ['zh', 'en']) test(`Eikona pages ${width}px ${lang}`, async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(`/eikona-pages?width=${width}&lang=${lang}`)
  const tabs = page.getByRole('tab')
  await expect(tabs).toHaveCount(3)
  const capabilityTitle = page.getByText(lang === 'zh' ? '图像服务状态' : 'Image service status', { exact: true })
  await expect(capabilityTitle).toBeVisible()
  await expect(page.getByText(lang === 'zh' ? '服务尚未就绪，请检查 Eikona 配置' : 'Service not ready; check Eikona settings', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: lang === 'zh' ? '生成图像' : 'Generate images', exact: true })).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Fixture prompt' }).fill('保留选定版本的生成草稿')
  await page.getByLabel(lang === 'zh' ? '提示词 ID' : 'Prompt ID', { exact: true }).fill('prompt-fixture')
  await page.getByLabel(lang === 'zh' ? '固定版本' : 'Fixed version', { exact: true }).fill('2')
  await page.getByRole('button', { name: lang === 'zh' ? '添加变量' : 'Add variable', exact: true }).click()
  await page.getByLabel(lang === 'zh' ? '变量名 1' : 'Variable name 1', { exact: true }).fill('subject')
  await page.getByLabel(lang === 'zh' ? '变量内容 1' : 'Variable content 1', { exact: true }).fill('山川\n云雾')
  const saveDraft = page.getByRole('button', { name: lang === 'zh' ? '保存生成草稿' : 'Save generation draft', exact: true })
  await saveDraft.focus()
  await page.keyboard.press('Enter')
  await expect.poll(() => page.evaluate(() => (window as unknown as { draftWrites: unknown[] }).draftWrites.length)).toBe(1)
  await expect(saveDraft).toBeEnabled()
  expect(await page.evaluate(() => (window as unknown as { preparationCalls: unknown[] }).preparationCalls.length)).toBe(0)
  expect(await page.locator('#fixture').evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath(`eikona-draft-${width}-${lang}.png`), fullPage: true })
  const promptField = page.getByLabel(lang === 'zh' ? '提示词 ID' : 'Prompt ID', { exact: true })
  await promptField.dispatchEvent('compositionstart', { data: '' })
  await promptField.press('Enter')
  expect(await page.evaluate(() => (window as unknown as { preparationCalls: unknown[] }).preparationCalls.length)).toBe(0)
  await promptField.dispatchEvent('compositionend', { data: 'prompt-fixture' })
  await page.getByLabel(lang === 'zh' ? '固定版本' : 'Fixed version', { exact: true }).press('Enter')
  await expect(page.getByText(lang === 'zh' ? '准备已创建；费用未知，执行需要另行批准。' : 'Preparation created. Cost is unknown; execution requires separate approval.', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => (window as unknown as { preparationCalls: unknown[] }).preparationCalls)).toEqual([{ prompt_id: 'prompt-fixture', prompt_version: 2, values: { subject: '山川\n云雾' }, controls: { model_ref: 'openai/gpt-5.4-image-2', candidate_count: 1 } }])
  await tabs.nth(1).click()
  await expect(page.getByText('Fixture candidates', { exact: true })).toBeVisible()
  await page.keyboard.press('End')
  await expect(tabs.nth(2)).toBeFocused()
  await expect(page.getByText('Fixture assets', { exact: true })).toBeVisible()
  await expect(capabilityTitle).toBeHidden()
  expect(await page.evaluate(() => (window as unknown as { assetReads: unknown[] }).assetReads.length)).toBe(0)
  await page.getByRole('button', { name: lang === 'zh' ? '加载资产' : 'Load assets', exact: true }).click()
  await expect(page.getByText('First fixture asset', { exact: true })).toBeVisible()
  await expect(page.getByText(lang === 'zh' ? '版本待核验' : 'Version not verified', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: lang === 'zh' ? '下一页' : 'Next page', exact: true }).click()
  await expect(page.getByText('Second fixture asset', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: lang === 'zh' ? '上一页' : 'Previous page', exact: true }).click()
  await expect(page.getByText('First fixture asset', { exact: true })).toBeVisible()
  expect(await page.locator('#fixture').evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath(`eikona-assets-${width}-${lang}.png`), fullPage: true })
  await tabs.nth(2).focus()

  await page.keyboard.press('Home')
  await expect(tabs.nth(0)).toBeFocused()
  await expect(page.getByRole('textbox', { name: 'Fixture prompt' })).toHaveValue('保留选定版本的生成草稿')
  await expect(page.getByLabel(lang === 'zh' ? '提示词 ID' : 'Prompt ID', { exact: true })).toHaveValue('prompt-fixture')
  expect(await page.locator('#fixture').evaluate(node => node.scrollWidth <= node.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath(`eikona-pages-${width}-${lang}.png`), fullPage: true })
  expect(errors).toEqual([])
})
