import { test, expect } from '@playwright/test'

for (const width of [360, 560, 960]) test(`Ordo project ${width}: attention, graph, details and safe action`, async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', error => { errors.push(error.message); console.error('Project fixture browser error:', error.message) })
  await page.goto(`/ordo-project?width=${width}`)
  await expect(page.getByRole('tab', { name: '待处理' })).toHaveAttribute('aria-selected', 'true')
  await page.screenshot({ path: testInfo.outputPath(`ordo-attention-${width}.png`), fullPage: true })
  await page.getByRole('button', { name: /Task 4/ }).click()
  await expect(page.getByRole('complementary', { name: '对象详情' })).toBeVisible()
  await page.getByRole('button', { name: '请求停止' }).focus()
  await page.keyboard.press('Enter')
  expect(await page.evaluate(() => (window as any).ordoFixture.calls.length)).toBe(0)
  await page.getByRole('button', { name: '确认提交' }).click()
  await expect.poll(() => page.evaluate(() => (window as any).ordoFixture.calls.length)).toBe(1)
  await page.getByRole('button', { name: '返回列表' }).click()
  await page.getByRole('tab', { name: '任务图' }).click()
  await expect(page.locator('.react-flow__node').first()).toBeVisible()
  await page.getByLabel('搜索任务').fill('Task 4')
  await page.getByText('Task 4 · blocked', { exact: true }).click()
  if (width === 960) await expect.poll(async () => (await page.locator('.react-flow__node.selected').boundingBox())?.width ?? 0).toBeGreaterThan(80)
  const box = await page.locator('[data-ordo-project]').boundingBox()
  expect(box!.width).toBeLessThanOrEqual(width)
  expect(await page.locator('[data-ordo-project]').evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath(`ordo-project-${width}.png`), fullPage: true })
  await page.evaluate(async () => { (window as any).ordoFixture.fail = true; await (window as any).ordoFixture.controller.poll() })
  await expect(page.getByText(/连接中断/)).toBeVisible()
  expect(errors).toEqual([])
})
