import { test, expect } from '@playwright/test'

for (const width of [360, 560, 960]) test(`canvas ${width}px edits, saves and reopens without submitting work`, async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(`/project-canvas?width=${width}`)
  await page.getByRole('button', { name: '创建画布', exact: true }).click()
  await page.getByRole('button', { name: '文字草稿', exact: true }).click()
  const draft = page.getByRole('textbox', { name: '文字草稿', exact: true })
  await draft.fill('画布恢复测试')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByText('已确认保存', { exact: true })).toBeVisible()
  await page.locator('#remount').click()
  await expect(draft).toHaveValue('画布恢复测试')
  await expect(page.locator('.react-flow__minimap')).toBeVisible()
  await expect(page.locator('.react-flow__node')).toHaveCount(1)
  expect(await page.evaluate(() => (window as unknown as { canvasWrites: number }).canvasWrites)).toBe(1)
  await page.screenshot({ path: testInfo.outputPath(`canvas-${width}.png`), fullPage: true })
  expect(errors).toEqual([])
})

test('canvas drag is one undo step and camera undo restores the viewport', async ({ page }) => {
  await page.goto('/project-canvas?width=960')
  await page.getByRole('button', { name: '创建画布', exact: true }).click()
  await page.getByRole('button', { name: '文字草稿', exact: true }).click()
  const node = page.locator('.react-flow__node')
  const before = await node.boundingBox()
  expect(before).not.toBeNull()
  await page.mouse.move(before!.x + 50, before!.y + 14)
  await page.mouse.down()
  await page.mouse.move(before!.x + 120, before!.y + 64, { steps: 5 })
  await page.mouse.up()
  await expect.poll(async () => (await node.boundingBox())!.x).toBeGreaterThan(before!.x + 40)
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect.poll(async () => Math.abs((await node.boundingBox())!.x - before!.x)).toBeLessThan(1)
  await page.getByRole('button', { name: '重做', exact: true }).click()
  await expect.poll(async () => (await node.boundingBox())!.x).toBeGreaterThan(before!.x + 40)
  const viewport = page.locator('.react-flow__viewport')
  const transform = await viewport.getAttribute('style')
  await page.locator('.react-flow__controls-zoomin').click()
  await expect.poll(() => viewport.getAttribute('style')).not.toBe(transform)
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect.poll(() => viewport.getAttribute('style')).toBe(transform)
})
